[build]
command = "npm run build"
publish = "client/dist"

[functions]
directory = "server/netlify/functions"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api"
status = 200

[[redirects]]
from = "/product/:id"
to = "/kurs/:id"
status = 301
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[dev]
command = "npm run client:dev"
targetPort = 5173
port = 8888
