[build]
command = "npm run build"
publish = "client/dist"

[functions]
directory = "server/netlify/functions"

# API
[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api"
status = 200

# Permanent redirect
[[redirects]]
from = "/product/:id"
to = "/kurs/:id"
status = 301
force = true

# Cache headers
[[headers]]
for = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*"
  [headers.values]
  Cache-Control = "public, max-age=60, must-revalidate"

# SPA-fallback (måste ligga sist)
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
