[build]
base = ""
command = "npm run build"
publish = "client/dist"

[functions]
directory = "server/netlify/functions"

[[redirects]]
from = "/api/courses"
to = "/.netlify/functions/api/courses"
status = 200

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api"
status = 200

[[redirects]]
from = "/product/:id"
to = "/kurs/:id"
status = 301
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
